services:
  - type: web
    name: fluentia-attendance-system
    env: docker
    plan: free
    numInstances: 1
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: PORT
        value: "5000"
